"use client";
import RecommendationCard from "@/components/report/recommendation-card";
import SeverityChart from "@/components/charts/severity-chart";

import ScoreGauge from "@/components/charts/score-gauge";
import { useAdvice } from "@/hooks/useAdvice";
import { useEffect, useState } from "react";
import ExecutiveSummary from "@/components/report/executive-summary";
import ScoreCard from "@/components/report/score-card";
import SeverityCard from "@/components/report/severity-card";
import FindingsList from "@/components/report/findings-list";

export default function ReportPage() {
  const [report, setReport] =
    useState<any>(null);

    const {
    advice,
    generate,
    } = useAdvice();

    useEffect(() => {
        if (
            report &&
            report.findings.length > 0
        ) {
            generate(
            report.findings[0].title
            );
        }
    }, [report]);

  useEffect(() => {
    const stored =
      sessionStorage.getItem(
        "scanResult"
      );

    if (stored) {
      setReport(
        JSON.parse(stored)
      );
    }
  }, []);

  if (!report) {
    return (
      <main className="p-20">
        Loading Report...
      </main>
    );
  }

  const critical =
    report.findings.filter(
      (f: any) =>
        f.severity === "critical"
    ).length;

  const high =
    report.findings.filter(
      (f: any) =>
        f.severity === "high"
    ).length;

  const medium =
    report.findings.filter(
      (f: any) =>
        f.severity === "medium"
    ).length;

  const low =
    report.findings.filter(
      (f: any) =>
        f.severity === "low"
    ).length;

  return (
    <main className="mx-auto max-w-7xl px-6 py-20">
      <div className="mb-10">
            <h1 className="text-5xl font-bold">
                Security Report
            </h1>

            <p className="mt-2 text-slate-400">
                Generated by ShieldScan
            </p>
        </div>
      {/* <ExecutiveSummary
        score={report.score}
      /> */}
      <ScoreCard
        score={report.score}
      />

      <div className="mt-8 grid gap-4 md:grid-cols-4">
        <SeverityCard
          label="Critical"
          count={critical}
        />

        <SeverityCard
          label="High"
          count={high}
        />

        <SeverityCard
          label="Medium"
          count={medium}
        />

        <SeverityCard
          label="Low"
          count={low}
        />
      </div>
      {/* <div className="mt-8 grid gap-6 lg:grid-cols-2">
        <ScoreGauge
          score={report.score}
        />

        <SeverityChart
          critical={critical}
          high={high}
          medium={medium}
          low={low}
        />
      </div> */}

      <section className="mt-12">
        <h2 className="mb-6 text-3xl font-bold">
          Findings
        </h2>

        <FindingsList
          findings={
            report.findings
          }
        />
      </section>
      <section className="mt-10">
        {advice && (
            <RecommendationCard
            content={advice}
            />
        )}
        </section>

    </main>
  );
}