const demoReport = {
  score: 86,

  findings: [
    {
      title:
        "Content Security Policy Missing",
      severity: "high",
      description:
        "Header not found. Recommended: default-src 'self'; script-src 'self'; object-src 'none';",
    },

    {
      title:
        "Weak Referrer Policy",
      severity: "low",
      description:
        "Current policy exposes more referral information than recommended.",
    },

    {
      title:
        "Potential XSS Injection Point",
      severity: "low",
      description:
        "Search input detected and classified as a potential reflected XSS entry point.",
    },
  ],
};

function getGrade(score: number) {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  return "D";
}

export default function DemoPage() {
  const critical =
    demoReport.findings.filter(
      (f) =>
        f.severity ===
        "critical"
    ).length;

  const high =
    demoReport.findings.filter(
      (f) =>
        f.severity === "high"
    ).length;

  const medium =
    demoReport.findings.filter(
      (f) =>
        f.severity ===
        "medium"
    ).length;

  const low =
    demoReport.findings.filter(
      (f) =>
        f.severity === "low"
    ).length;

  return (
    <main className="min-h-screen bg-[#0B0F14] text-white">
      <div className="container mx-auto px-8 py-10">

        <h1 className="text-5xl font-bold">
          Security Report
        </h1>

        <p className="mt-2 text-slate-400">
          Sample report generated by
          ShieldScan
        </p>

        {/* Score Card */}

        <div className="mt-10 rounded-3xl border border-[#2A3136] bg-[#14181C] p-10">

          <p className="text-lg text-slate-300">
            Security Score
          </p>

          <div className="mt-8 flex items-center gap-6">

            <span className="text-6xl font-bold text-[#7FA58E]">
              {demoReport.score}
            </span>

            <div className="rounded-xl bg-[#183224] px-6 py-3 text-lg text-[#7FA58E]">
              Grade {getGrade(
                demoReport.score
              )}
            </div>

          </div>
        </div>

        {/* Stats */}

        <div className="mt-8 grid gap-6 md:grid-cols-4">

          <div className="rounded-3xl border border-[#2A3136] bg-[#14181C] p-6">
            <p className="text-lg text-slate-300">
              Critical
            </p>

            <p className="mt-4 text-6xl font-bold">
              {critical}
            </p>
          </div>

          <div className="rounded-3xl border border-[#2A3136] bg-[#14181C] p-8">
            <p className="text-2xl text-slate-300">
              High
            </p>

            <p className="mt-4 text-6xl font-bold">
              {high}
            </p>
          </div>

          <div className="rounded-3xl border border-[#2A3136] bg-[#14181C] p-8">
            <p className="text-2xl text-slate-300">
              Medium
            </p>

            <p className="mt-4 text-6xl font-bold">
              {medium}
            </p>
          </div>

          <div className="rounded-3xl border border-[#2A3136] bg-[#14181C] p-8">
            <p className="text-2xl text-slate-300">
              Low
            </p>

            <p className="mt-4 text-4xl font-bold">
              {low}
            </p>
          </div>

        </div>

        {/* Findings */}

        <div className="mt-14">

          <h2 className="text-3xl font-bold">
            Findings
          </h2>

          <div className="mt-8 space-y-6">

            {demoReport.findings.map(
              (
                finding,
                index
              ) => (
                <div
                  key={index}
                  className="rounded-xl border border-[#2A3136] bg-[#14181C] p-8"
                >
                  <div className="flex items-start justify-between gap-4">

                    <div>

                      <h3 className="text-xl font-semibold">
                        {finding.title}
                      </h3>

                      <p className="mt-4 text-sm text-slate-400">
                        {
                          finding.description
                        }
                      </p>

                    </div>

                    <span className="rounded-full border border-[#2D5A43] px-4 py-2 capitalize text-[#7FA58E]">
                      {
                        finding.severity
                      }
                    </span>

                  </div>
                </div>
              )
            )}

          </div>
        </div>

        {/* AI Summary */}

        <div className="mt-14 rounded-3xl border border-[#2A3136] bg-[#14181C] p-10">

          <h2 className="text-2xl font-bold">
            AI Security Summary
          </h2>

          <p className="mt-6 text-sm leading-8 text-slate-400">
            The application shows a generally
            good security posture but lacks a
            Content Security Policy, increasing
            exposure to client-side attacks.
            Additional improvements are
            recommended for browser security
            headers and input validation.
          </p>

        </div>

      </div>
    </main>
  );
}